### ISSUE TITLE
Modernizr included twice?

### ISSUE THREAD

**Issue by doublemarked** [yeoman/generator-webapp#259]
I have just started using your generator, so please forgive me if I've overlooked something. However, in my recently scaffolded project (using the tip of `master`), Modernizr appears to be included twice - once in the `<head>` and again in the footer scripts,

```
    <!-- build:js scripts/vendor/modernizr.js -->
    <script src="/bower_components/modernizr/modernizr.js"></script>
    <!-- endbuild -->
  </head>

 [...]

    <!-- build:js scripts/vendor.js -->
    <!-- bower:js -->
    <script src="bower_components/modernizr/modernizr.js"></script>
    <script src="bower_components/jquery/dist/jquery.js"></script>
    <!-- endbower -->
    <!-- endbuild -->
```

I did a production build and was able to confirm it referenced twice there, as well. Is this intentional?

**Comment by silvenon** [comment]
No, I fixed this in 390199858f3bda1647856fd3b3a7704601e4e0a0 (not released yet). My bad :smiley:

**Comment by doublemarked** [comment]
Thanks for the prompt reply. I'm running the tip of ``master``, however, which includes that patch. Yet the problem still exists.

**Comment by silvenon** [comment]
I see the problem. The initial wiredep call has the wrong regex. If you were to run `gulp wiredep`, your paths would be corrected and the 2nd Modernizr would be excluded.

Try with the latest commits. (I also corrected Bootstrap paths, wasn't really an issue, just for consistency.)

**Comment by doublemarked** [comment]
Looks good - thanks!

**Comment by jnsq** [comment]
It seems like this issue is back with the actual release (v2.3.2) ?

**Comment by silvenon** [comment]
@jnsq why do you think it's back? I checked the `index.html` file and the built JS file, I see it included only once. Could you share more details?

**Comment by jnsq** [comment]
@silvenon i've just done a `yo webapp`, and a `gulp wiredep`, and i can see in the `index.html` the modernizr.js script import in the header inside `<!-- build:js scripts/vendor/modernizr.js --><!-- endbuild -->`, and also at the bottom just after jquery.js script import inside `<!-- build:js scripts/vendor.js --><!-- bower:js --><!-- endbower --><!-- endbuild -->`.

bower@1.8.0
generator-webapp@2.3.2
gulp-cli@1.2.2
yo@1.8.5

**Comment by silvenon** [comment]
@jnsq yep, you're right! Reopening…

**Comment by illycz** [comment]
Some news about fix? Thanks...

generator-webapp@2.4.1

**Comment by silvenon** [comment]
Sorry, getting around to it… 😅

**Comment by nithinM** [comment]
This fixed the issue.
```
gulp.src('app/*.html')
.pipe(wiredep({
  exclude: ['bower_components/modernizr/modernizr.js'],
  ignorePath: /^(\.\.\/)*\.\./
}))
.pipe(gulp.dest('app'));
```

**Comment by silvenon** [comment]
Should be fine in [v4.0.0-0](https://github.com/yeoman/generator-webapp/releases/tag/v4.0.0-0).
